objects/Account.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>false</enableHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Assigned_Cleaner__c.object
<CustomObject><fields>
        <fullName>Cleaner__c</fullName>
        <label>Cleaner</label>
        <referenceTo>Cleaner__c</referenceTo>
        <relationshipLabel>Assigned Cleaners</relationshipLabel>
        <relationshipName>Assigned_Cleaners</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Jobs__c</referenceTo>
        <relationshipLabel>Assigned Cleaners</relationshipLabel>
        <relationshipName>Assigned_Cleaners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Executed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Information about cleaners</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Assigned Cleaner</label><nameField>
        <displayFormat>C -{000000}</displayFormat>
        <label>Assigned Cleaner Number</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Assigned Cleaners</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Cleaner__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Cleaner</label><nameField>
        <label>Cleaner Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Cleaners</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Invoice__c.object
<CustomObject><fields>
        <fullName>Cleaner__c</fullName>
        <label>Cleaner</label>
        <referenceTo>Cleaner__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Settled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Holds all the paid info for each Cleaner</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Invoice</label><nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Invoices</pluralLabel><sharingModel>ControlledByParent</sharingModel><startsWith>Vowel</startsWith></CustomObject>

objects/Jobs__c.object
<CustomObject><fields>
        <fullName>Booking_Datetime__c</fullName>
        <label>Booking Datetime</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Booking_Frequency__c</fullName>
        <label>Booking Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>One Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Job_Type__c</fullName>
        <label>Job Type</label>
        <picklist>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B&amp;B</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>This object contains all the data related to Jobs(Cost, Time, Number of cleaners etc).</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Jobs</label><nameField>
        <displayFormat>J-{0000000}</displayFormat>
        <label>Jobs Number</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Jobs</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/JobServiceTest.cls
@isTest
public class JobServiceTest 
{
    public static List<Account> newAccounts = new List<Account>();
    public static List<Cleaner__c> newCleaners = new List<Cleaner__c>();
    public static List<Jobs__c> newJobs = new List<Jobs__c>();
    public static List<Assigned_Cleaner__c> newAssignedCleaners = new List<Assigned_Cleaner__c>();
    public static Integer ACCOUNTSIZE = 5;
    public static Integer JOBSIZE = 2;
    static void setupData()
    {
        //create accounts
        for(Integer i=1; i<=ACCOUNTSIZE; i++)
        {
            Account newAccount = new Account(Name = 'Test Account '+i);
            newAccounts.add(newAccount);
        }
        insert newAccounts;
        
        //create Cleaners
        for(Integer i=1; i<=ACCOUNTSIZE; i++)
        {
            Cleaner__c newCleaner = new Cleaner__c();
            newCleaner.Name = 'Test Cleaner'+i;
            newCleaner.Active__c = true;
            newCleaners.add(newCleaner);
        }
        insert newCleaners;
        
        
        for(Account theAccount : newAccounts)
        {
            for(Integer i=1; i<=JOBSIZE; i++)
            {
                Jobs__c newJob = new Jobs__c();
                newJob.Client__c = theAccount.Id;
                newJob.Job_Type__c = 'Home';
                newJob.Booking_DateTime__c = system.now().addDays(2);
                newJob.Booking_Frequency__c = 'Monthly';
                newJob.Status__c = 'Booked';
                newJobs.add(newJob);
            }
        }
        insert newJobs;
        
        for(Jobs__c theJob : newJobs)
        {
            integer i =1;
            Assigned_Cleaner__c newCleaner = new Assigned_Cleaner__c();
            if(i>ACCOUNTSIZE)
                i=0;
            newCleaner.Cleaner__c = newCleaners[i].Id;
            newCleaner.Job__c = theJob.Id;
			i++;
            newAssignedCleaners.add(newCleaner);
        }
        insert newAssignedCleaners;
    }
    
    static testMethod Void ececuteJobsTest()
    {
        setupData();
        List<Id> jobIds = new List<Id>();
        for(Jobs__c theJob : newJobs)
        {
            theJob.Status__c = 'Executed';
            jobIds.add(theJob.ID);
        }
        
        Test.startTest();
        	update newJobs;
        Test.stopTest();
        
        List<Jobs__c> updatedJobs = [Select ID, Status__c FROm Jobs__c];
        system.assertEquals(JOBSIZE*ACCOUNTSIZE*2, updatedJobs.size(), 'Since jobs are weekly a new set of jobs should be created');
        
        List<Assigned_Cleaner__c> updatesAssignedCleaners = [SELECT Id, Status__c FROM Assigned_Cleaner__c];
        for(Assigned_Cleaner__c theCleaner : updatesAssignedCleaners)	
            system.assertEquals('Executed', theCleaner.Status__c);
    }
    
    static testMethod Void invoiceCreateBatchTest()
    {
        setupData();
        List<Id> jobIds = new List<Id>();
        for(Jobs__c theJob : newJobs)
        {
            theJob.Status__c = 'Executed';
            jobIds.add(theJob.ID);
        }
        update newJobs;
        
        Test.startTest();
        	Database.ExecuteBatch(new GenerateJobInvoicesBatch());
        Test.stopTest();
        
        List<Invoice__c> createdInvoices= [Select ID FROM Invoice__c];
        system.assertEquals(ACCOUNTSIZE,createdInvoices.Size() );
    }

}