objects/Assigned_Cleaner__c.object
<CustomObject><fields>
        <fullName>Cleaner__c</fullName>
        <label>Cleaner</label>
        <referenceTo>Cleaner__c</referenceTo>
        <relationshipLabel>Assigned Cleaners</relationshipLabel>
        <relationshipName>Assigned_Cleaners</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Job_Executed_Date__c</fullName>
        <label>Job Executed Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Revenue__c</fullName>
        <label>Revenue</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Executed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Information about cleaners</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Assigned Cleaner</label><nameField>
        <displayFormat>C -{000000}</displayFormat>
        <label>Assigned Cleaner Number</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Assigned Cleaners</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Cleaner__c.object
<CustomObject><fields>
        <fullName>Amount_Due__c</fullName>
        <formula>Revenue_Earned__c -  Amount_Paid__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Cleaner</label><nameField>
        <label>Cleaner Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Cleaners</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Invoice__c.object
<CustomObject><fields>
        <fullName>Cleaner__c</fullName>
        <label>Cleaner</label>
        <referenceTo>Cleaner__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Settled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Holds all the paid info for each Cleaner</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Invoice</label><nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Invoices</pluralLabel><sharingModel>ControlledByParent</sharingModel><startsWith>Vowel</startsWith></CustomObject>

classes/GenerateJobInvoicesBatch.cls
global class GenerateJobInvoicesBatch implements Database.Batchable<sObject>
{
    String query;
    Date sysDate = System.Today();
	global GenerateJobInvoicesBatch()
    {
        Date queryMinDate;
        Date queryMaxDate = sysDate.addDays(-1);
        if(Test.isRunningTest())
        {
            queryMinDate = sysDate.addDays(-1);
            queryMaxDate = sysDate.addDays(1);
        }
        else if(sysDate.day() == 1)
        {
            queryMinDate = Date.newInstance(sysDate.year(),sysDate.Month()-1 , 15);
        }
        else If(sysDate.day() == 15)
        {
            queryMinDate = Date.newInstance(sysDate.Year(),sysDate.month(), 1);
        }
       
            
        query = 'SELECT ID, (SELECT ID, Job_Executed_Date__c, Revenue__c, Cleaner__c FROM Assigned_Cleaners__r';
        query = query + ' WHERE Job_Executed_Date__c >= '+String.ValueOf(queryMinDate)+' AND Job_Executed_Date__c <= '+String.ValueOf(queryMaxDate);
        query = query + ' AND Status__c = \'Executed\'),';
        query = query + 'Amount_Due__c FROM Cleaner__c';
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        system.debug(query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Cleaner__C> scope)
    {
        List<Assigned_Cleaner__c> cleanersToupdate = new List<Assigned_Cleaner__c>();
        List<Invoice__c> invoicesToInsert = new List<Invoice__c>();
        
        for(Cleaner__c theCleaner : scope)
        {
            Decimal amountDue = 0;
            for(Assigned_Cleaner__c theAssignedCleaner : theCleaner.Assigned_Cleaners__r)
            {
                amountDue = amountDue + theAssignedCleaner.Revenue__c;
                theAssignedCleaner.Status__c = 'Created';
            }
            Invoice__c newInvoice  = new Invoice__c();
            newInvoice.Cleaner__c = theCleaner.Id;
            newInvoice.Invoice_Amount__c = amountDue;
            newInvoice.Invoice_Date__c = system.Today();
            newInvoice.Status__c = 'Created';
            invoicesToInsert.add(newInvoice);
        }
        
        try
        {
            insert invoicesToInsert;
            update cleanersToUpdate;
        }
        catch(DMLException exp)
        {
            //do something
        }
    }
     global void finish(Database.BatchableContext BC) 
    {        
    }
}