objects/Assigned_Cleaner__c.object
<CustomObject><fields>
        <fullName>Job_Executed_Date__c</fullName>
        <label>Job Executed Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Jobs__c</referenceTo>
        <relationshipLabel>Assigned Cleaners</relationshipLabel>
        <relationshipName>Assigned_Cleaners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Revenue__c</fullName>
        <label>Revenue</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Executed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Information about cleaners</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Assigned Cleaner</label><nameField>
        <displayFormat>C -{000000}</displayFormat>
        <label>Assigned Cleaner Number</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Assigned Cleaners</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Jobs__c.object
<CustomObject><fields>
        <fullName>Booking_Datetime__c</fullName>
        <label>Booking Datetime</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Booking_Frequency__c</fullName>
        <label>Booking Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>One Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Employee_Revenue__c</fullName>
        <formula>If( ISPICKVAL( Status__c , 'Executed'), Gross_Cost__c /2,0 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Employee Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Job_Type__c</fullName>
        <label>Job Type</label>
        <picklist>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B&amp;B</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Number_Of_Cleaners__c</fullName>
        <label>Number Of Cleaners</label>
        <summaryForeignKey>Assigned_Cleaner__c.Job__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>This object contains all the data related to Jobs(Cost, Time, Number of cleaners etc).</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Jobs</label><nameField>
        <displayFormat>J-{0000000}</displayFormat>
        <label>Jobs Number</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Jobs</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/JobService.cls
public class JobService {

    public List<Jobs__c> findExecutedTasks(List<Jobs__c> updatedJobs, Map<Id,Jobs__c> oldJobsMap)
    {
        List<Jobs__c> executedJobs = new List<Jobs__c>();
        List<Jobs__c> jobsToInsert = new List<Jobs__c>();
        for(Jobs__c theJob : updatedJobs)
            if(theJob.Status__c == 'Executed' && oldJobsMap.get(theJob.ID).Status__c != 'Executed')
            {
                executedJobs.add(theJob);
                If(theJob.Booking_Frequency__c != 'One Time')
                {
                    Jobs__c newRecurringJob = new Jobs__c();
                    newRecurringJob.Client__c = theJob.Client__c;
                    newRecurringJob.Job_Type__c = theJob.Job_Type__c;
                    newRecurringJob.Booking_Frequency__c = theJob.Booking_Frequency__c;
                    newRecurringJob.Status__c = 'Booked';
                    Integer frequencyDays = 0;
                    if(theJob.Booking_Frequency__c == 'Weekly')
                        frequencyDays = 7;
                    if(theJob.Booking_Frequency__c == 'Bi-weekly')
                        frequencyDays = 14;
                    if(theJob.Booking_Frequency__c == 'Monthly')
                        frequencyDays = 30;
                    newRecurringJob.Booking_Datetime__c = theJob.Booking_Datetime__c.addDays(frequencyDays);
                    jobsToInsert.add(newRecurringJob);
                }
            }
            	
        try
        {
            system.debug(jobsToInsert);
            Insert jobsToInsert;
        }
        catch(DMLException dmlExp)
        {
            //Do Something
        }
        return executedJobs;
        
    }
    
    public void processExecutedTasks(List<Jobs__c> executedJobs)
    {
        List<Id> jobIds = new List<Id>(new Map<Id, Jobs__c>(executedJobs).keySet());
        List<Assigned_Cleaner__c> assignedCleaners = new List<Assigned_Cleaner__c>();
        if(!jobIds.isEmpty())
            assignedCleaners = [SELECT ID, Revenue__c,Job__c, Job__r.Employee_Revenue__c, Job__r.Number_Of_Cleaners__c  FROM Assigned_Cleaner__c WHERE Job__r.Id In: jobIds];
        
        for(Assigned_Cleaner__c theAssignedCleaner : assignedCleaners)
        {
            theAssignedCleaner.Revenue__c = theAssignedCleaner.Job__r.Employee_Revenue__c/theAssignedCleaner.Job__r.Number_Of_Cleaners__c;
            theAssignedCleaner.Job_Executed_Date__c = system.today();
            theAssignedCleaner.Status__c = 'Executed'; 
        }
        
        try
        {
            Update assignedCleaners;
        }
        Catch(DMLException exp)
        {
            //send email or throw visual error
        }
    }
}