objects/Product2.object
<CustomObject><fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields><fields>
        <fullName>Current_Inventory__c</fullName>
        <label>Current Inventory</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Lifespan_Months__c</fullName>
        <label>Lifespan Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Maintenance_Cycle__c</fullName>
        <description>Number of days required before routine maintenance is needed</description>
        <label>Maintenance Cycle (Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Replacement_Part__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Replacement Part</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Warehouse_SKU__c</fullName>
        <externalId>true</externalId>
        <label>Warehouse SKU</label>
        <length>100</length>
        <type>Text</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>false</enableFeeds></CustomObject>

classes/WarehouseCalloutServiceTest.cls
@isTest
private class WarehouseCalloutServiceTest {
  // implement your mock callout test here
    testMethod Static void test(){
        List<EquipmentWrapperFromJSON> ListEWFS = new List<EquipmentWrapperFromJSON>();
        List<Product2> listProduct = new List<Product2>();
        Product2 p = new Product2();
        p.Replacement_Part__c = true;
        p.Name = 'testing';
        p.Cost__c = 10;
        p.Current_Inventory__c = 5;
        p.Lifespan_Months__c = 2;
        p.Maintenance_Cycle__c = 60;
        p.Warehouse_SKU__c = '10001';
        listProduct.add(p);

        insert listProduct;

        test.startTest();
            //ListEWFS = WarehouseCalloutService.wrapWquipment();
            Test.setMock(HttpCalloutMock.class, new WarehouseCalloutServiceMock());
            WarehouseCalloutService.runWarehouseEquipmentSync();
        test.stopTest();
        Upsert listProduct;
    }
    
    testmethod static void testMaintenenceTrigger()
    {
        case theCase = new Case();
        theCase.Type = 'Repair';
        insert theCase;
        
        theCase.Status = 'Closed';        
        update theCase;
    }
    
    testMethod Static void tesScedulet(){
        List<EquipmentWrapperFromJSON> ListEWFS = new List<EquipmentWrapperFromJSON>();
        List<Product2> listProduct = new List<Product2>();
        Product2 p = new Product2();
        p.Replacement_Part__c = true;
        p.Name = 'testing';
        p.Cost__c = 10;
        p.Current_Inventory__c = 5;
        p.Lifespan_Months__c = 2;
        p.Maintenance_Cycle__c = 60;
        p.Warehouse_SKU__c = '10001';
        listProduct.add(p);

        insert listProduct;

        test.startTest();
            //ListEWFS = WarehouseCalloutService.wrapWquipment();
            Test.setMock(HttpCalloutMock.class, new WarehouseCalloutServiceMock());
            String CRON_EXP = '0 0 0 15 3 ? 2022';
            System.schedule('ScheduleApexClassTest', CRON_EXP, new  WarehouseSyncSchedule());
        test.stopTest();
        Upsert listProduct;
    }
}